{{- if .Values.cpuWorkers.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ray-cluster.fullname" . }}-cpu-workers
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      ray.io/node-type: worker
      ray.io/resource-type: cpu
---
{{- end }}
{{- if or .Values.gpuWorkers.enabled (gt (len .Values.gpuWorkerGroups) 0) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ray-cluster.fullname" . }}-gpu-workers
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      ray.io/node-type: worker
      ray.io/resource-type: gpu
{{- end }}
