fullnameOverride: ray-cluster

head:
  rayStartParams:
    dashboard-host: "0.0.0.0"
    num-cpus: "1"
    object-store-memory: "536870912"

  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "3Gi"

  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    exec:
      command: ["bash", "-c", "wget -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success && wget -T 2 -q -O- http://localhost:8265/api/gcs_healthz | grep success"]

  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    exec:
      command: ["bash", "-c", "wget -T 2 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success && wget -T 2 -q -O- http://localhost:8265/api/gcs_healthz | grep success"]

cpuWorkers:
  replicas: 1
  minReplicas: 1
  maxReplicas: 2
  nodeSelector: null

  rayStartParams:
    num-cpus: "1"
    object-store-memory: "536870912"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

gpuWorkers:
  enabled: false

gpuWorkerGroups:
  - groupName: inference
    replicas: 0
    minReplicas: 0
    maxReplicas: 2
    rayStartParams: {}
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "1"
        memory: "2Gi"
        nvidia.com/gpu: "1"
    volumeMounts:
      - name: ray-tmp
        mountPath: /tmp/ray
    volumes:
      - name: ray-tmp
        emptyDir:
          medium: Memory
    nodeSelector:
      ray.io/resource-type: gpu
      gpu-group: inference
    tolerations:
      - key: nvidia.com/gpu
        operator: Equal
        value: "true"
        effect: NoSchedule
    topologySpreadConstraints: []
    labels:
      ray.io/node-type: worker
      ray.io/resource-type: gpu
      gpu-group: inference
      app: ray
      component: gpu-worker
    initContainers: []
  - groupName: training
    replicas: 0
    minReplicas: 0
    maxReplicas: 1
    rayStartParams: {}
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "2"
        memory: "4Gi"
        nvidia.com/gpu: "1"
    volumeMounts:
      - name: ray-tmp
        mountPath: /tmp/ray
    volumes:
      - name: ray-tmp
        emptyDir:
          medium: Memory
    nodeSelector:
      ray.io/resource-type: gpu
      gpu-group: training
    tolerations:
      - key: nvidia.com/gpu
        operator: Equal
        value: "true"
        effect: NoSchedule
    topologySpreadConstraints: []
    labels:
      ray.io/node-type: worker
      ray.io/resource-type: gpu
      gpu-group: training
      app: ray
      component: gpu-worker
    initContainers: []
